backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main

media_folder: "src/images"
public_folder: "/images"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow

collections:
  - label: "Galerie"
    name: "galerie"
    folder: "src/categories"
    create: true
    delete: true
    editor:
      preview: false
    fields:
      - { label: "Catégorie", name: "categorie", widget: "string"}
      - { label: "Tag", name: "tag", widget: "string" }
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image", media_library: { config: { multiple: true } } }

  # Add other collections as needed

  - label: "Tarifs & Prestations"
    name: "tarifs"
    folder: "src/prestations"
    create: true
    delete: true
    editor:
      preview: false
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Prix", name: "price", widget: "string"}

  - label: "Paramètres"
    name: "parametres"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "nav-items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: "Title", name: "text", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }

      - label: "Footer"
        name: "footer-items"
        file: "src/_data/footer.yaml"
        fields:
          - label: Footer Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: "Title", name: "text", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
